name: Build and relase image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.8' # The Go version to download (if necessary) and use.
    - run: scripts/version
    - run: |
        export LINKFLAGS="-extldflags -static -s"
        mkdir -p bin/
    - name: Build controller
      run: CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/terraform-controller
    - name: Build executor
      run: CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/terraform-executor ./pkg/executor
    - uses: docker/build-push-action@v1
      name: build/push - controller
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: absaoss/terraform-controller
        path: ./bin
        dockerfile: package/Dockerfile.controller
        tag_with_ref: true
    - uses: docker/build-push-action@v1
      name: build/push - executor
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: absaoss/terraform-controller-executor
        path: ./bin
        dockerfile: package/Dockerfile.executor
        tag_with_ref: true
    - name: compute-tag
      id: tag
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
        echo ::set-output name=semver::${GITHUB_REF#refs/tags/v}
    - uses: stefanprodan/helm-gh-pages@v1.4.1
      with:
        token: ${{ secrets.REPO_TOKEN }}
        charts_dir: chart
        branch: gh-pages
        linting: off
        app_version: ${{ steps.tag.outputs.tag}}
        chart_version: ${{ steps.tag.outputs.semver }}
